version: '3'
services:
  app:
    build: .
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "80:80"
    depends_on:
      - app
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

